import React from 'react'
import "./day47.scss"

const Day47 = () => {
    const handleClick = (e) => {
        if(e.target.classList.contains("day47__pixel")) e.target.classList.toggle("click")
    }    
    return (
        <div onClick={handleClick} className='day47 days'> 
            {/* `Fila 1` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 2` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 3` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 4` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 5` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 6` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 7` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 8` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel  click'></div>
            <div className='day47__pixel  click'></div>
            <div className='day47__pixel  click'></div>
            <div className='day47__pixel  click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 9` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 10` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 11` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 12` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 13` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 14` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 15` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 16` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            {/* `Fila 17` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 18` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 19` */}
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            {/* `Fila 20` */}
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel click'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
            <div className='day47__pixel'></div>
        </div>
    )
}

export default Day47